### ISSUE TITLE
Disable WebApp Submissions

### ISSUE THREAD

**Issue by jsws** [ISISScientificComputing/autoreduce#1]
Give Admin users the option to disable the submission of jobs in the webapp.
This can be used when, for instance the Queue Processor is under maintenance and we don't want users to submit new jobs but want them to be able to browse past jobs.

**Comment by ElliotAOram** [comment]
Need to decide if this is still relevant @jsws @Anders-Markvardsen

**Comment by Anders-Markvardsen** [comment]
With the new setup I will vote for this issue is no longer relevant.

But, it could come in handy to have the easy way as an admin to put a temporary notices on the webapp. Like, "Under maintenance until ..." or "WebApp is being prepared for the next cycle" and so on. Just looked and under Admin there is a Notifications option but it does not seem to do anything; I added the notification "Under maintenance until ..." and was hoping it would then get displayed on the front webapp page. Do you see this also?

**Comment by ElliotAOram** [comment]
Ah yes I did see this notification. We should update the text on it as we are now in cycle.
I will close this issue now as it no longer appears to be relevant.
![image](https://user-images.githubusercontent.com/13132128/40905446-dbf2b432-67d5-11e8-9785-0a8de1206902.png)
