### ISSUE TITLE
Move certain instrument settings out of settings files.

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#1036]
Issue raised by: [developer]

As discussed with @dtasev 
### What?
To further reduce and simplify the number of settings within autoreduction and to make testing easier.

- [ ] Remove `VALID_INSTRUMENTS` setting (Creates single source of truth for instruments) #1047
- [ ] Remove `FLAT_OUTPUT_INSTRUMENTS` setting (Simplification) 
- [ ] Make flat output option a field on the instrument table (Simplification)
- [ ] Prevent the database reset script from removing instruments (Prevent changing instrument PK IDs between every cycle)

### Where?
Updates to various places.

### How to test the issue is resolved
Functionality should remain unchanged with more tests

**Comment by dtasev** [comment]
I'm looking at removing `VALID_INSTRUMENTS` from the queue processor at least in #1022. Most of it is easy except for the `scripts/mantid/properties.py` usage, of which I can't find a reference anywhere else from the repo, probably because it's a script. Any idea if that script is used anywhere else or if it's good to go? @Anders-Markvardsen might know something about this script usage too

**Comment by Anders-Markvardsen** [comment]
'scripts/mantid/properties.py' is in principle a good idea, the idea being e.g. to make easier to update the mantid properties files before cycles. However, it has not been used since manual updating been relatively easy. In the future, it could be that a modified version of this script could become part of an install / configuration onto compute nodes I wonder. For now please just remove reference to 'import VALID_INSTRUMENTS' and suggest simply replace it with list of instrument names, say '['WISH', 'GEM'...]' that the user of the script needs to adjust as needed.

About 'multiThreaded.MaxCores=6' :-) Some tests was done when the compute node was first bought, but not many. Likely room for improvement here also
