### ISSUE TITLE
Slow response with WebApp when expanding to see runs

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#216]
Observation. As of today it took 6 seconds after clicking on > WISH to see the all the WISH runs from 41156 to 42667.  

This only takes this long the first time expanding an instrument in a new session or after clicking on "All Jobs". 

This issue is to work on making this faster, down to 1 second or less.

**Comment by Anders-Markvardsen** [comment]
I have put this issue at low priority since at the moment there are other more urgent issues

**Comment by ElliotAOram** [comment]
This is because these runs are loaded from the database. The more runs, the longer the load time. The way to avoid this is pagination, however I think we should look into a full re-write of the interface as it no longer makes sense in the way it is currently formatted. (Due to the expansion of the number of instruments)

**Comment by ElliotAOram** [comment]
This should be split into something more manageable

**Comment by ElliotAOram** [comment]
Design - #297 
Implementation - #298 

With the creation of these issues, I will close this issue
