### ISSUE TITLE
Plotting in the Webapp

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#217]
After discussion at NOBUGS18 with SNS, In webapp plotting could be the key to getting more drive from the user to want to use autoreduction. Their approach is to use plotly to plot mantid output mainly from plot1D. 

To do this in ISIS autoreduce, we would be limited to either adding mantid onto the django node, or storing plots in the database

**Comment by Anders-Markvardsen** [comment]
From speak to Muon beamline scientist Peter Baker.
There might be an additional competitive benefit of adding plotting to the Webapp. To stay up to date with the beamline as data comes off the beamline. For some instrument, like for muon beamline, what I understood from Peter is that it would be useful to simply just have an app which can show plots of raw data or something very nearly just raw data. I.e. here the attraction is a static image rather than reduced data. Such a tool does not seem to be currently available, but would be trivially to provide when this issue is fixed.

**Comment by ElliotAOram** [comment]
closing in favour of creating more granular issues
