### ISSUE TITLE
WebApp: Re-run are not added next to their original runs

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#41]
When you re-run a run using the webapp, the runs do not appear next to the original run (see the screen shot below) 

![image](https://user-images.githubusercontent.com/13132128/39362241-a7b3cc68-4a1d-11e8-941f-8b1aa427fbde.png)

**Comment by jsws** [comment]
Runs are displayed in chronological order by the time they were submitted (if I remember correctly) and because of issue #22 jobs re-run using the web app appear at the correct time where as runs submitted by the end of run monitor appear an hour ahead. This makes it look like re-ran jobs are placed randomly in the displayed list.

**Comment by ElliotAOram** [comment]
Ahhhhhhh good point in which case lets close this as a side effect of the time zone issue
