### ISSUE TITLE
Make the webapp a secure webpage

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#435]
Issue raised by: [developer]

### What?
currently the webapp although internal is a non-secure webpage and this can be easily noticed by visiting the site in firefox or chrome. To put users at ease, the webpage should be secure.

### Where?
Webapp + SSL certificate

### How?
Noticed during daily checks

### Reproducible?
Yes - simply visit the web app and look in the address bar

### How to test the issue is resolved
* We may have to investigate what is the standard procedure at STFC for getting SSL certificates. ICAT / TOPCAT already have one so we can ask them. 

* Visit the webpage and ensure it is SSL secure.

**Comment by rickybassom** [comment]
Requested a certificate from Digital Infrastructure. For reference: https://staff.stfc.ac.uk/core/security/information/Pages/ApplyingforaServerCertificate.aspx

**Comment by rickybassom** [comment]
Certificate is installed and is visible on a web browser at https://reduce.isis.cclrc.ac.uk/. HTTP connections are also forwarded to HTTPS. Port `:80` to `:443`. I will document the process of added a certificate. The current certificate expires on 16/02/2022.

The user office is throwing a 500 error _I think_ because the `https://` version of the site is not added to their list of trusted servers.

**Comment by rickybassom** [comment]
https://github.com/isisbusapps/Users/issues/2417#issuecomment-789710194

**Comment by rickybassom** [comment]
Link to wiki page https://github.com/ISISScientificComputing/autoreduce/wiki/SSL-Certificates

**Comment by dtasev** [comment]
I think this is finished now

**Comment by dtasev** [comment]
Nope

**Comment by rickybassom** [comment]
This issue is still open isisbusapps/Users#2417

**Comment by rickybassom** [comment]
The issue above with the UO has been fixed now
