### ISSUE TITLE
File read in Mantid script

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#56]
An increasing number of runs on `GEM` and `POLARIS` are failing with in the mantid script execution with the following error message similar to the one seen [here](http://reduce.isis.cclrc.ac.uk/runs/84597/0/) 

My initial guess is that this could be related to the `lastrun.txt` file updating too early (before file write has finished) however, there may be a slightly deeper issue here as t appears to only be happening with the isis_powder instruments.

Re-running these jobs fixes the issue, but because they fail in the mantid script, the automatic job re-runner does not attempt to do this.

A simple solution would be to check that file can be read before we push to the mantid script. If this resolves the issue, then we should feed this back into the controls team as it might be that lastrun.txt is updating before file write completion.

![image](https://user-images.githubusercontent.com/13132128/39857639-ef5f5024-542b-11e8-80b9-8724e52242b2.png)

**Comment by ElliotAOram** [comment]
Next try to actually read the file (not just check file permissions) before passing data location to mantid script

**Comment by ElliotAOram** [comment]
Monitor this in the new release. If it occurs then prepare fix for maintenance day

**Comment by DavidFair** [comment]
Opened a new issue [#22638 - Mantid](https://github.com/mantidproject/mantid/issues/22638) to allow passing filenames instead of run numbers, since `os.path.exists` always returns true on failing runs

**Comment by DavidFair** [comment]
Fixed - on production the following changes were made

- Switched `datasearch.searcharchive=off` in `/opt/...` and `/home/isisautoreduce...`
- Removed all `datasearch.directories` in `/opt/...` and appended `/isis/cycle_18_1/NDX[POLARIS/GEM]` to the `Mantid.user.properties` in `/home/isisautoreduce/....` since this config value overrides the installed one with Mantid

We should monitor, but I am strongly confident in these changes

**Comment by DavidFair** [comment]
Instead of using `/isis/cycle_x_y/NDXINST/` we use the full path: `/isis/NDXInst/instrument/data/cycle_x_y/` similar to what the queue processor gives us. This avoids various issues with DFS and matches our view to that of the end of run monitor.

Also I ended up using MantidPlot with X11 forwarding to reset the configuration file, then I copied this over to the autoreduce account replacing the original. This ensured that config was in a known working state
