### ISSUE TITLE
Add allowed status fields to access.get_status

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#606]
Issue raised by: [developer]

### What?
In the database we have an enum style Status table. This table is designed to only ever hold set values:
`Complete`, `Error`, `Processing`, Queued` and `Skipped`. As such we should ensure that when calling get_status we only allow these values. 

For this issue try to use Test Driven development (TDD)
1. Add a test to `models/database/access/tests/test_access.py` that attempts to call `get_status` with a `status_value` of `"test"`. The test should use the `assertraises(<exception>, <function>, <input_value>) format as we expect if an unexpected value such as `"test"` is passed to `get_status` it should fail.
2. Run the test and see that it fails.
2. Add code to `models/database/access.py` function `get_status` to check the status_value is one of the above allowed values. If it is not an allowed value, then we should raise an exception, the best choice is probably a `ValueError`. 

### Where?
Test file: `models/database/access/tests/test_access.py`
source file: `models/database/access.py`

### How?
This is a generic code improvement to the project

### How to test the issue is resolved
* Code review to ensure that the unit test is properly formed
* Ensure the unit test passes on Travis

**Comment by keiranjprice101** [comment]
@ElliotAOram would it be better, instead of not allowing invalid statuses to be given to `get_status`, we raise an error if it does not exist and create is false. The number of trips to the database wont be reduced, but if we check the value before going to the database we will need to duplicate the statuses. Unless I am misunderstanding something.

As a side note `get_status` is only called by `status_utils._get_status()` with `create` always set to true.
