### ISSUE TITLE
Remove unacceptable user facing folder/file structure accidentally introduced 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#764]
Issue raised by: [developer/user]

### What?
Observed during smoke testing before ISIS cycle 20_2.

This user facing change likely accidentally occurred during implementation of webapp plotting.

See picture 

![unnamed](https://user-images.githubusercontent.com/1135476/92581714-eeda1d80-f287-11ea-84eb-2c8a2493623b.png)

The new user offending part which has accidentally been introduced is that is a new directory is created for every run submitted to a RB number with the unhelpful user facing numbering 0, 1, 2, ... In this example the user will see in /instrument/MUSR/RBNumber/RB1920237/autoreduced:

```
0/
1/
```

whereas the correct and previously behaviour for this instrument (which is 'labelled' as an `excitation` instrument, name 'excitation' here separate issue to change this name in queue processors setting file):

```
files for reduction of run 80968
files for reduction of run 80969
reduction_log/  (which contains the logs from the reduction)
```

Note if instrument not labelled as 'excitaiton` instrument the output would have been (for the above example):

```
80968/
80969/
```
i.e. where extra sub-folders are run numbers. This is useful for those instruments producing masses of files for each run.

To reproduce:

1. Run any manual submission job, e.g. `python manual_submission.py MUSR 80968` and  `python manual_submission.py MUSR 80969` (note in picture above reduce.py is setup with dummy reduction script that simply copies the raw data file)

Purpose of this issue is the revert back to the previous way of outputting reduction files and logs, while accommodating the new webapp plotting.

### Where?
Probably needs both changes to queue processors code and webapp code

### Reproducible?
Yes

### How to test the issue is resolved
A set of instructions / A script / Include test files if required

**Comment by keiranjprice101** [comment]
This folder structure is produced in `PostProcessAdmin#_new_reduction_path`.

The numbers are the version of the run (i.e the first run will produce `/autoreduced/0` the second `/autoreduced/1` and so on)
This will only happen if overwrite is off (It is by default off in a manual submission and a user can set this themself in the webapp as well)

This structure works fine for instruments which have a run number in their output i.e `/autoreduced/run_number/run_version`.
For Instruments which do not produce a run number folder the output is as above. 

The issue is if we remove the run version folder, it will no longer be possible to rerun a job without overwriting the previous run. I

**Comment by keiranjprice101** [comment]
Based on discussion:
- Rerunning without overwriting will only be allowed for non flat structure.
- Hide this option in Webapp for flat structure instruments
- run version folders from `/0/` -> `/run-version-0` etc.
