### ISSUE TITLE
Help Navigation broken

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#788]
Issue raised by: [developer]

### What?
The help navigation is broken See gif
![help-vansih](https://user-images.githubusercontent.com/44777678/94448515-e304bb80-01a2-11eb-94fa-7147e364989a.gif)
This happens for me on chrome and with any of the side links

### Where?
`WebApp/autoreduce_webapp/templates/help.html` 

### How?
How did the issue come about

### Reproducible?
[Yes]

### How to test the issue is resolved
The navigation links should move the user to the correct section.

**Comment by rickybassom** [comment]
I'll take a look at this. I suspect it's to do with the removal of the search bar.

**Comment by rickybassom** [comment]
Can can be fixed by un-commenting https://github.com/ISISScientificComputing/autoreduce/blob/master/WebApp/autoreduce_webapp/templates/help.html#L17 .

The bug was introduced here https://github.com/ISISScientificComputing/autoreduce/pull/702. It was commented out because of the poor text search accuracy. Search is implemented by filtering topics according to keywords ([example](https://github.com/ISISScientificComputing/autoreduce/blob/master/WebApp/autoreduce_webapp/templates/help.html#L64)). A solution could be to increase the keywords or auto-generate keywords from the topic body.

**Comment by rickybassom** [comment]
Topic modelling can be used to generate keywords for topics to improve search. Something like [Latent Dirichlet Allocation](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation)?

**Comment by rickybassom** [comment]
@Anders-Markvardsen please can you suggest how I might improve the search? I suggested a couple of approaches above.

**Comment by Anders-Markvardsen** [comment]
Uumm yes... look forward to when we have Selenium testing in place and this introduced bug would have be been spotted by the change in #702 . Maybe need to start this sooner..., and reminder added to discuss in next sprint review.


@rickybassom for this I would be happy with any of the following

* re-introduce the search box with a quick attempt by you to improve its search function (sorry I am not familiar with Latent Dirichlet Allocation, but will trust you know more than me on this)
* Find a way to fix this issue, but without re-introducing the search function
* Re-introducing the search function (since better to have a poor text search box than a bug in help pages)

**Comment by rickybassom** [comment]
Here's what I'll do:
- Continue with having the search disabled and fix the help navigation in a PR.
- Add in comments in the code to the issue below where the search is commented out.
- Open an issue to re-enable search filtering and improve the search filtering using topic modelling or another appropriate method. I would be happy to tackle this issue as I have experience in natural language processing and topic modelling.
