### ISSUE TITLE
Variables set in the web interface are not being used by the reduction

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#870]
Issue raised by: user

### What?
The variables set in the web interface are not being used by the reduction.

It turned out that the webserver is passing the correct information to the python reduction process but that the dictionary update was not happening.

### Where?
https://github.com/ISISScientificComputing/autoreduce/blob/master/queue_processors/autoreduction_processor/post_process_admin.py#L120

### How?
Seems like leftover code during switch from Python 2 to 3! `map` is lazy in Python 3 and the result WILL NOT BE computed unless it's used in a for loop, or other sequence call (e.g. calling `list(map(merge_dicts, ["standard_vars", "advanced_vars"])`)

### Reproducible?
Yes

### How to test the issue is resolved
See comment below

**Comment by mducle** [comment]
You can test it on the dev server with MARI by re-running a reduction and changing the "Advanced Variables" `hard_mask_file` from `mari_mask2020_2.xml` to `None` and run the reduction. Look in the reduction log once it has completed and you should see an entry for `Value of: hard_mask_file is set to: None` instead of the full path to the xml file.
